x:
  name: joint2_motor
  max: 0.315
  min: -0.315
  deadzone: 0.02
  max_vel: 0.5
  reverse_input: true
  lock_output: false
  lock_output_value: 0.0

y:
  name: joint1_motor
  max: 0.315
  min: -0.315
  deadzone: 0.02
  max_vel: 0.5
  reverse_input: false
  lock_output: false
  lock_output_value: 0.0

z:
  name: joint0_motor
  max: 0.5
  min: -0.5
  deadzone: 0.05
  max_vel: 1.0
  reverse_input: false
  lock_output: false
  lock_output_value: 0.0